// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	CreateGodo(ctx context.Context, arg CreateGodoParams) (Godo, error)
	GetGodo(ctx context.Context, id int64) (Godo, error)
	ListGodos(ctx context.Context) ([]Godo, error)
	UpdateGodoDone(ctx context.Context, arg UpdateGodoDoneParams) error
}

var _ Querier = (*Queries)(nil)
